import type { Metadata } from "next";
import OutputBasedQuestions from "@/components/OutputBasedQuestions";

export const metadata: Metadata = {
  title: "JavaScript Output Based Questions",
  description:
    "Practice JavaScript output-based questions with concise explanations. Ideal for interviews and quick concept checks on scope, hoisting, closures, async, and more.",
  keywords: [
    "javascript output based questions",
    "js output based questions",
    "javascript interview output questions",
    "javascript output questions with answers",
    "javascript console output questions",
    "javascript output quiz",
    "javascript output quiz with answers",
    "javascript output mcq",
    "javascript output mcq questions",
    "javascript output based mcq",
    "javascript output based quiz",
    "javascript output based coding questions",
    "javascript output interview questions",
    "javascript output questions for interviews",
    "javascript output questions for beginners",
    "javascript output questions for advanced",
    "javascript output questions for experienced",
    "javascript tricky output questions",
    "javascript tricky output problems",
    "javascript output questions with explanations",
    "javascript output based questions with explanations",
    "javascript output questions and answers",
    "js output questions and answers",
    "javascript output snippets",
    "javascript output practice",
    "javascript output practice problems",
    "javascript output based practice",
    "javascript output based practice questions",
    "javascript console output practice",
    "javascript console output quiz",
    "javascript interview practice output",
    "javascript interview practice questions",
    "javascript interview mcq",
    "javascript interview mcq questions",
    "javascript interview mcq with answers",
    "javascript logical questions",
    "javascript logical output questions",
    "javascript logical mcq",
    "javascript coding output questions",
    "javascript coding output mcq",
    "javascript output questions on hoisting",
    "javascript output questions on scope",
    "javascript output questions on closures",
    "javascript output questions on this",
    "javascript output questions on prototypes",
    "javascript output questions on promises",
    "javascript output questions on async await",
    "javascript output questions on event loop",
    "javascript output questions on arrays",
    "javascript output questions on strings",
    "javascript output questions on objects",
    "javascript output questions on map set",
    "javascript output questions on destructuring",
    "javascript output questions on modules",
    "javascript output questions on generators",
    "javascript output questions on async generators",
    "javascript output questions on optional chaining",
    "javascript output questions on nullish coalescing",
    "javascript output questions on truthy falsy",
    "javascript output questions on type coercion",
    "javascript output questions on equality",
    "javascript output questions on strict mode",
    "javascript output questions on classes",
    "javascript output questions on inheritance",
    "javascript output questions on closures and scope",
    "javascript output questions on call apply bind",
    "javascript output questions on functions",
    "javascript output questions on arrow functions",
    "javascript output questions on rest spread",
    "javascript output questions on template literals",
    "javascript output questions on tagged templates",
    "javascript output questions on map reduce filter",
    "javascript output questions on reduce",
    "javascript output questions on setTimeout",
    "javascript output questions on setInterval",
    "javascript output questions on promises race all",
    "javascript output questions on error handling",
    "javascript output questions on try catch finally",
    "javascript output questions on parsing json",
    "javascript output questions on json parse",
    "javascript output questions on parseInt",
    "javascript output questions on Number.isNaN",
    "javascript output questions on isNaN",
    "javascript output questions on Object.defineProperty",
    "javascript output questions on Object.freeze",
    "javascript output questions on Object.seal",
    "javascript output questions on Object.entries",
    "javascript output questions on Object.fromEntries",
    "javascript output questions on Proxy",
    "javascript output questions on Symbol",
    "javascript output questions on private class fields",
    "javascript output questions on destructuring arrays",
    "javascript output questions on destructuring objects",
    "javascript output questions on spread operator",
    "javascript output questions on rest parameters",
    "javascript output questions on short circuiting",
    "javascript output questions on logical operators",
    "javascript output questions on ternary",
    "javascript output questions on optional chaining",
    "javascript output questions on nullish",
    "javascript output questions on array methods",
    "javascript output questions on array length",
    "javascript output questions on array holes",
    "javascript output questions on array flatten",
    "javascript output questions on flat",
    "javascript output questions on padStart",
    "javascript output questions on Intl.NumberFormat",
    "javascript output questions on eval",
    "javascript output questions on delete operator",
    "javascript output questions on typeof",
    "javascript output questions on instanceof",
    "javascript output questions on reference vs value",
    "javascript output questions on mutation",
    "javascript output questions on immutability",
    "javascript output questions on iterators",
    "javascript output questions on generators",
    "javascript output questions on for in vs for of",
    "javascript output questions on event propagation",
    "javascript output questions on dom events",
    "javascript output questions on browser apis",
    "javascript output questions on sessionStorage",
    "javascript output based interview questions 2025",
    "javascript output based interview questions 2026",
    "online javascript output questions",
    "javascript online output quiz",
    "free javascript output questions",
    "javascript output questions with explanations pdf",
    "javascript output questions with answers pdf",
  ],
  alternates: { canonical: "/javascript/output-based-questions" },
};

export default function JavascriptOutputBasedQuestionsPage() {
  return <OutputBasedQuestions />;
}
