import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://www.codecompileronline.com'
  const now = new Date()
  const tutorialSlugs = [
    "history-of-javascript",
    "how-javascript-works",
    "javascript-in-browser-vs-nodejs",
    "setting-up-javascript-environment",
    "writing-your-first-javascript-program",
    "javascript-syntax",
    "comments-in-javascript",
    "variables/var-let-const",
    "variables/scope",
    "variables/hoisting",
    "variables/data-types",
    "variables/primitive-types",
    "variables/non-primitive-types",
    "variables/type-conversion",
    "variables/typeof-operator",
    "variables/dynamic-typing",
    "operators",
    "operators/arithmetic-operator",
    "operators/assignment-operator",
    "operators/comparison-operator",
    "operators/logical-operator",
    "operators/bitwise-operator",
    "operators/ternary-operator",
    "operators/nullish-coalescing-operator",
    "operators/optional-chaining-operator",
    "operators/precedence-operator",
    "conditionals",
    "conditionals/if-statement",
    "conditionals/if-else",
    "conditionals/else-if-ladder",
    "conditionals/switch-statement",
    "loops",
    "loops/for-loop",
    "loops/while-loop",
    "loops/do-while-loop",
    "loops/break-statement",
    "loops/continue-statement",
    "loops/nested-loops",
    "functions",
    "functions/function-declaration",
    "functions/function-expression",
    "functions/arrow-functions",
    "functions/parameters-arguments",
    "functions/default-parameters",
    "functions/rest-parameters",
    "functions/spread-operator",
    "functions/callback-functions",
    "functions/higher-order-functions",
    "functions/pure-functions",
    "functions/iife",
    "functions/recursion",
    "arrays",
    "arrays/array-methods",
    "arrays/map",
    "arrays/filter",
    "arrays/reduce",
    "arrays/find",
    "arrays/findindex",
    "arrays/every",
    "arrays/sort",
    "arrays/slice",
    "arrays/flat",
    "arrays/foreach",
    "arrays/destructuring",
    "arrays/multidimensional",
    "objects",
    "strings",
    "strings/template-literals",
    "dom-manipulation",
    "events",
    "async/promises",
    "async/async-await",
    "closures",
    "classes",
    "this-keyword",
    "interview-questions",
    "array-methods",
    "data-types",
    "spread-operator",
    "template-literals",
    "scope",
    "promises",
    "async-await",
    "execution-context/event-loop",
    "closures/lexical-scope",
    "closures/scope-chain",
    "closures/module-pattern",
    "es6/destructuring",
    "es6/spread-rest",
  ]

  return [
    {
      url: baseUrl,
      lastModified: now,
      changeFrequency: 'daily',
      priority: 1,
    },
    {
      url: `${baseUrl}/html/online-compiler`,
      lastModified: now,
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: `${baseUrl}/javascript/online-compiler`,
      lastModified: now,
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: `${baseUrl}/formatter/online-compiler`,
      lastModified: now,
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    {
      url: `${baseUrl}/regex/online-compiler`,
      lastModified: now,
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: `${baseUrl}/javascript`,
      lastModified: now,
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    {
      url: `${baseUrl}/privacy`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.3,
    },
    {
      url: `${baseUrl}/about`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.4,
    },
    {
      url: `${baseUrl}/terms`,
      lastModified: now,
      changeFrequency: 'yearly',
      priority: 0.2,
    },
    {
      url: `${baseUrl}/contact`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.3,
    },
    ...tutorialSlugs.map((slug) => ({
      url: `${baseUrl}/javascript/${slug}`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    })),
  ]
}
